// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzEYLaA2t_TeHSYotqygRYgq4YDm8ZVo0',
    appId: '1:605260406155:web:6fde0eea35e2b2a710638e',
    messagingSenderId: '605260406155',
    projectId: 'findup-f7f07',
    authDomain: 'findup-f7f07.firebaseapp.com',
    storageBucket: 'findup-f7f07.firebasestorage.app',
    measurementId: 'G-D7P5H1WZ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgDpatkseCaiYlg8cqscUMg-hOizh8NM',
    appId: '1:605260406155:android:63031430d319cad110638e',
    messagingSenderId: '605260406155',
    projectId: 'findup-f7f07',
    storageBucket: 'findup-f7f07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5MBILIs59UhSTEH8VIaFrG8RrnBRyZw',
    appId: '1:605260406155:ios:f69f40bde17eb24e10638e',
    messagingSenderId: '605260406155',
    projectId: 'findup-f7f07',
    storageBucket: 'findup-f7f07.firebasestorage.app',
    androidClientId: '605260406155-gvgneogj3anpqsngr9b7lniuoj9i74jc.apps.googleusercontent.com',
    iosClientId: '605260406155-soh1dp1oh5cehn7mqa7nmot4d3qbmvg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.findupMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5MBILIs59UhSTEH8VIaFrG8RrnBRyZw',
    appId: '1:605260406155:ios:f69f40bde17eb24e10638e',
    messagingSenderId: '605260406155',
    projectId: 'findup-f7f07',
    storageBucket: 'findup-f7f07.firebasestorage.app',
    androidClientId: '605260406155-gvgneogj3anpqsngr9b7lniuoj9i74jc.apps.googleusercontent.com',
    iosClientId: '605260406155-soh1dp1oh5cehn7mqa7nmot4d3qbmvg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.findupMvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzEYLaA2t_TeHSYotqygRYgq4YDm8ZVo0',
    appId: '1:605260406155:web:a6700601dd0657ba10638e',
    messagingSenderId: '605260406155',
    projectId: 'findup-f7f07',
    authDomain: 'findup-f7f07.firebaseapp.com',
    storageBucket: 'findup-f7f07.firebasestorage.app',
    measurementId: 'G-V0MNX6HQWH',
  );
}
